from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'listings', views.ListingViewSet, basename='listing')
router.register(r'bookings', views.BookingViewSet, basename='booking')
router.register(r'reviews', views.ReviewViewSet, basename='review')

# The API URLs are now determined automatically by the router
urlpatterns = [
    path('api/', include(router.urls)),
]

# URL patterns generated by the router:
# 
# Listings:
# GET    /api/listings/                    - List all listings
# POST   /api/listings/                    - Create a new listing
# GET    /api/listings/{id}/               - Retrieve a specific listing
# PUT    /api/listings/{id}/               - Update a specific listing
# PATCH  /api/listings/{id}/               - Partially update a specific listing
# DELETE /api/listings/{id}/               - Delete a specific listing
# GET    /api/listings/by_location/        - Filter listings by location
# GET    /api/listings/by_price_range/     - Filter listings by price range
# GET    /api/listings/my_listings/        - Get current user's listings
#
# Bookings:
# GET    /api/bookings/                    - List all bookings (filtered by user)
# POST   /api/bookings/                    - Create a new booking
# GET    /api/bookings/{id}/               - Retrieve a specific booking
# PUT    /api/bookings/{id}/               - Update a specific booking
# PATCH  /api/bookings/{id}/               - Partially update a specific booking
# DELETE /api/bookings/{id}/               - Delete a specific booking
# POST   /api/bookings/{id}/confirm/       - Confirm a booking (host only)
# POST   /api/bookings/{id}/cancel/        - Cancel a booking (guest or host)
# GET    /api/bookings/my_bookings/        - Get current user's bookings as guest
# GET    /api/bookings/host_bookings/      - Get bookings for user's listings
#
# Reviews:
# GET    /api/reviews/                     - List all reviews
# POST   /api/reviews/                     - Create a new review
# GET    /api/reviews/{id}/                - Retrieve a specific review
# PUT    /api/reviews/{id}/                - Update a specific review
# PATCH  /api/reviews/{id}/                - Partially update a specific review
# DELETE /api/reviews/{id}/                - Delete a specific review
# GET    /api/reviews/by_listing/          - Get reviews for a specific listing
# GET    /api/reviews/my_reviews/          - Get current user's reviews
